[project]
name = "uv-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sajad Hatami", email = "sajadhatamiw@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "django>=6.1",
]

[project.scripts]
uv-test = "uv_test:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
